#pragma once

#include "PluginProcessor.h"
#include <juce_gui_basics/juce_gui_basics.h>
// Include BinaryData header (generated by CMake)
#include <BinaryData.h>

class GravityWellAudioProcessorEditor : public juce::AudioProcessorEditor,
                                        private juce::Timer {
public:
  GravityWellAudioProcessorEditor(GravityWellAudioProcessor &);
  ~GravityWellAudioProcessorEditor() override;

  void paint(juce::Graphics &) override;
  void resized() override;

  void timerCallback() override;

private:
  GravityWellAudioProcessor &audioProcessor;

  juce::Slider speedSlider;
  juce::Label speedLabel;

  juce::Slider gravitySlider;
  juce::Label gravityLabel;

  std::unique_ptr<juce::AudioProcessorValueTreeState::SliderAttachment>
      speedAttach;
  std::unique_ptr<juce::AudioProcessorValueTreeState::SliderAttachment>
      gravityAttach;
  std::unique_ptr<juce::AudioProcessorValueTreeState::SliderAttachment>
      dustAmtAttach;
  std::unique_ptr<juce::AudioProcessorValueTreeState::SliderAttachment>
      dustDensAttach;

  juce::TextButton helpButton{"?"};
  juce::Label helpOverlay;
  bool showHelp = false;

  juce::Slider dustAmtSlider;
  juce::Label dustAmtLabel;
  juce::Slider dustDensSlider;
  juce::Label dustDensLabel;

  juce::Image bgImage;

  JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(GravityWellAudioProcessorEditor)
};
